name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest      
    steps:
    - name: update tools
      run: sudo apt-get update && sudo apt-get -qq install gcc-arm-none-eabi

    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: configure_sim
      run: make config MACHINE_TYPE=sim
    - name: make
      run: make && pip install -r requirements.txt && python simulator_cmds.py
    - name: make distcheck
      run: make distclean
    - name: configure_nrf
      run: make config MACHINE_TYPE=nrf5x/nrf52840
    - name: make
      run: make
    - name: make distcheck
      run: make distclean

