name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: get_submodule
      run: git submodule update --init --recusive 
    - name: configure
      run: make config MACHINE_TYPE=sim
    - name: make
      run: make
    - name: make distcheck
      run: make clean
